title: Alonzo Green
description: I am a data analyst apprentice with a passion for transforming complex data into actionable insights. I specialize in Python and R for data manipulation, visualization, and statistical analysis. I'm always looking for new challenges to grow my skills and contribute to meaningful projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
