title: Alonzo
logo: doc/assets/IMG_4752.jpeg
description: Data Analyst Apprentice
show_downloads: true
theme: jekyll-theme-hacker

remote_theme: "pages-themes/hacker@v0.2.0"
plugins:
  - jekyll-remote-theme
